version: '3.4'

services:
  azwebcontainer:
    image: azwebcontainer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      APPCONFIG: https://firmusapitesterconfig.azconfig.io
    ports:
      - 7000:8080
      - 9229:9229
    command: [ "node", "--inspect=0.0.0.0:9229", "index.js" ]
