version: "3.9"
services:
  web:
    environment:
      - APPCONFIG=https://firmusapitesterconfig.azconfig.io
    build: .
    ports:
      - "7000:8080"
    volumes:
      - ~/.azure:/home/root/.azure
 